replicaCount: 4

image:
  repository: 534670738035.dkr.ecr.eu-north-1.amazonaws.com/cloud-native-devops-platform
  tag: "e9fad04552832758df30a27291676a7f9990c172"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

database:
  host: postgres
  port: 5432
  name: cloudapp
  user: devuser
  password: devpass

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70