replicaCount: 4

podAnnotations:
  gitops-demo: "v1"

image:
  repository: 534670738035.dkr.ecr.eu-north-1.amazonaws.com/cloud-native-devops-platform
  tag: "42d3b2bbef885afc2c374936d376e8d0c22b1865"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

database:
  host: postgres
  port: 5432
  name: cloudapp
  user: devuser
  password: devpass

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70