name: CI

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  ci:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::534670738035:role/GitHubActionsECRPushRole
          aws-region: eu-north-1

      - name: Verify AWS identity
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff

      - name: Run lint
        run: ruff check src tests

      - name: Run tests
        run: pytest

      - name: Build Docker image
        working-directory: .
        run: docker build -f docker/Dockerfile -t cloud-native-app:${{ github.sha }} .

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: cloud-native-app:${{ github.sha }}
          format: table
          scanners: vuln
          vuln-type: os,library
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: "0"
